/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipz80.validation;

import org.eclipse.xtext.validation.Check;

import uk.co.bithatch.eclipz80.asm.AsmPackage;
import uk.co.bithatch.eclipz80.asm.AsmProgram;
import uk.co.bithatch.eclipz80.scoping.AsmNamespaceSupport;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class AsmValidator extends AbstractAsmValidator {
	
	public static final String UNMATCHED_POP_NAMESPACE = "unmatchedPopNamespace";

	@Check
	public void checkNamespacePopBalance(AsmProgram program) {
		AsmNamespaceSupport.forEachUnmatchedPopNamespace(program, pop -> warning(
				"POP NAMESPACE has no matching PUSH NAMESPACE.",
				pop,
				AsmPackage.eINSTANCE.getPop_Register(),
				UNMATCHED_POP_NAMESPACE));
	}
}