/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipz80.generator;

import java.io.ByteArrayInputStream;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

import uk.co.bithatch.eclipz80.asm.AsmProgram;

/**
 * Generates a .bin file from Z80 assembly source on save.
 * Delegates to {@link Z80Assembler} for the actual encoding, then writes the
 * binary output via {@link IFileSystemAccess2}.
 */
public class AsmGenerator extends AbstractGenerator {

	@Override
	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		if (resource.getContents().isEmpty()) {
			return;
		}
		AsmProgram program = (AsmProgram) resource.getContents().get(0);

		// Compute output filename: replace .asm extension with .bin
		String sourceFileName = resource.getURI().lastSegment();
		String outputFileName = replaceExtension(sourceFileName, ".bin");

		Z80Assembler assembler = Z80Assembler.builder()
				.withSourceFileName(sourceFileName)
				.build();
		byte[] binary = assembler.assemble(program);

		// Log any warnings
		for (String warning : assembler.getWarnings()) {
			System.err.println("[Z80Assembler] WARNING: " + warning);
		}

		// Write binary via fsa (goes to src-gen/ by default, or configured output)
		fsa.generateFile(outputFileName, new ByteArrayInputStream(binary));
	}

	private String replaceExtension(String filename, String newExt) {
		int dot = filename.lastIndexOf('.');
		if (dot >= 0) {
			return filename.substring(0, dot) + newExt;
		}
		return filename + newExt;
	}
}