package uk.co.bithatch.eclipz88dk.toolchain;

import java.io.File;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.eclipse.cdt.core.model.CoreModel;
import org.eclipse.cdt.core.settings.model.ICConfigurationDescription;
import org.eclipse.cdt.core.settings.model.ICProjectDescription;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IncrementalProjectBuilder;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.ILog;
import org.eclipse.core.runtime.IProgressMonitor;

import uk.co.bithatch.bitzx.LanguageSystem;

/**
 * A builder that participates in {@code CLEAN_BUILD} to remove extra artifacts
 * that CDT's default clean doesn't know about:
 * <ul>
 *   <li>{@code *.c.asm} — intermediate files left by {@code zcc --assemble-only}</li>
 *   <li>Output format files ({@code .nex}, {@code .tap}, {@code .sna}, etc.)
 *       determined from {@code ILanguageSystemProvider.outputFormats()}</li>
 *   <li>{@code *_CODE.bin}, {@code *_UNASSIGNED.bin} and similar section binaries
 *       generated by z88dk</li>
 * </ul>
 * Files with {@code .img} extension are preserved (used for disk preparation).
 */
public class Z88DKCleanBuilder extends IncrementalProjectBuilder {

	public static final String BUILDER_ID = "uk.co.bithatch.eclipz88dk.cleanBuilder";

	private static final ILog LOG = ILog.of(Z88DKCleanBuilder.class);

	/** Extensions that must never be deleted during clean. */
	private static final Set<String> PRESERVED_EXTENSIONS = Set.of("img");

	@Override
	protected IProject[] build(int kind, Map<String, String> args, IProgressMonitor monitor) throws CoreException {
		if (kind == CLEAN_BUILD) {
			clean(monitor);
		}
		return null;
	}

	@Override
	protected void clean(IProgressMonitor monitor) throws CoreException {
		var project = getProject();
		if (project == null) return;

		/* Determine the build output directory (e.g. Debug/ or Release/) */
		File buildDir = getBuildDirectory(project);
		if (buildDir == null || !buildDir.isDirectory()) return;

		/* Collect extensions to clean from the language system provider */
		Set<String> extensionsToClean = new HashSet<>();
		extensionsToClean.add("c.asm");

		try {
			var langSys = LanguageSystem.languageSystem(project);
			if (langSys != null) {
				for (var fmt : langSys.outputFormats(project)) {
					var ext = fmt.extension();
					if (ext != null && !ext.isEmpty() && !PRESERVED_EXTENSIONS.contains(ext.toLowerCase())) {
						extensionsToClean.add(ext.toLowerCase());
					}
				}
			}
		} catch (Exception e) {
			LOG.warn("Z88DK Clean: could not query output formats, using defaults", e);
		}

		/* Always clean these common z88dk output extensions */
		extensionsToClean.add("nex");
		extensionsToClean.add("tap");
		extensionsToClean.add("sna");
		extensionsToClean.add("tzx");
		extensionsToClean.add("p");
		extensionsToClean.add("o");
		extensionsToClean.add("P");

		LOG.info("Z88DK Clean: cleaning build dir '" + buildDir + "' for extensions: " + extensionsToClean);

		int deleted = cleanBuildDirRecursive(buildDir, extensionsToClean);

		/* Also clean .c.asm files from the source tree — these are left by
		 * zcc --assemble-only next to the original .c files */
		deleted += cleanCasmFromSourceTree(project);

		if (deleted > 0) {
			project.refreshLocal(IProject.DEPTH_INFINITE, monitor);
		}
	}

	/**
	 * Get the build output directory for the active configuration.
	 */
	private File getBuildDirectory(IProject project) {
		try {
			ICProjectDescription projDesc = CoreModel.getDefault().getProjectDescription(project, false);
			if (projDesc != null) {
				ICConfigurationDescription cfgDesc = projDesc.getActiveConfiguration();
				if (cfgDesc != null) {
					var buildSetting = cfgDesc.getBuildSetting();
					if (buildSetting != null) {
						var outputEntries = buildSetting.getOutputDirectories();
						if (outputEntries != null && outputEntries.length > 0) {
							var outputPath = outputEntries[0].getFullPath();
							var outputFolder = project.getWorkspace().getRoot().getFolder(outputPath);
							if (outputFolder.exists()) {
								return outputFolder.getLocation().toFile();
							}
						}
					}
					/* Fallback: use configuration name as directory */
					var cfgName = cfgDesc.getName();
					var cfgDir = project.getLocation().append(cfgName).toFile();
					if (cfgDir.isDirectory()) return cfgDir;
				}
			}
		} catch (Exception e) {
			LOG.warn("Z88DK Clean: could not determine build directory", e);
		}
		return null;
	}

	/**
	 * Recursively clean the build directory, deleting files matching the
	 * given extensions and z88dk section binaries.
	 */
	private int cleanBuildDirRecursive(File dir, Set<String> extensionsToClean) {
		var files = dir.listFiles();
		if (files == null) return 0;

		int deleted = 0;
		for (File f : files) {
			if (f.isDirectory()) {
				deleted += cleanBuildDirRecursive(f, extensionsToClean);
				continue;
			}
			String name = f.getName();

			/* Skip preserved extensions */
			String ext = getExtension(name);
			if (ext != null && PRESERVED_EXTENSIONS.contains(ext.toLowerCase())) continue;

			boolean shouldDelete = false;

			/* 1. Match by collected output-format extensions */
			if (ext != null && extensionsToClean.contains(ext.toLowerCase())) {
				shouldDelete = true;
			}

			/* 2. Match *.c.asm */
			if (name.endsWith(".c.asm")) {
				shouldDelete = true;
			}

			/* 3. Match projectName_CODE.bin, projectName_UNASSIGNED.bin, etc. */
			if (name.matches(".*_[A-Z]+\\.bin")) {
				shouldDelete = true;
			}

			if (shouldDelete) {
				LOG.info("Z88DK Clean: deleting " + f.getAbsolutePath());
				if (f.delete()) {
					deleted++;
				}
			}
		}

		if (deleted > 0) {
			LOG.info("Z88DK Clean: deleted " + deleted + " extra artifact(s) from " + dir);
		}
		return deleted;
	}

	/**
	 * Walk the project source tree and delete any {@code .c.asm} files that
	 * were left behind by {@code zcc --assemble-only}.
	 */
	private int cleanCasmFromSourceTree(IProject project) {
		int[] count = { 0 };
		File projectDir = project.getLocation().toFile();
		cleanCasmRecursive(projectDir, count);
		return count[0];
	}

	private void cleanCasmRecursive(File dir, int[] count) {
		var files = dir.listFiles();
		if (files == null) return;
		for (File f : files) {
			if (f.isDirectory()) {
				cleanCasmRecursive(f, count);
			} else if (f.getName().endsWith(".c.asm")) {
				LOG.info("Z88DK Clean: deleting source-tree artifact " + f.getAbsolutePath());
				if (f.delete()) count[0]++;
			}
		}
	}

	private static String getExtension(String name) {
		int dot = name.lastIndexOf('.');
		return (dot >= 0 && dot < name.length() - 1) ? name.substring(dot + 1) : null;
	}
}
