source.. = src/,\
           src-gen/,\
           xtend-gen/
bin.includes = model/generated/,\
               .,\
               META-INF/,\
               plugin.xml
bin.excludes = **/*.mwe2,\
               **/*.xtend
additional.bundles = org.eclipse.xtext.xtext.generator,\
 org.eclipse.xtext.xbase,\
 org.eclipse.emf.mwe2.launch,\
 org.eclipse.emf.mwe2.lib,\
 org.eclipse.emf.mwe.utils,\
 org.eclipse.emf.codegen.ecore,\
 org.eclipse.emf.common,\
 org.eclipse.emf.ecore,\
 org.objectweb.asm,\
 org.apache.log4j,\
 org.eclipse.xtext.logging,\
 org.apache.commons.commons-logging
