/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.zxbasic.ui.contentassist;

import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class BasicProposalProvider extends AbstractBasicProposalProvider {
	
	@Override
	public void createProposals(ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		System.out.println("XXX createProposals "+ context);
		super.createProposals(context, acceptor);
	}
}
