/*
 * generated by Xtext 2.43.0
 */
package uk.co.bithatch.eclipzpp;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.parser.antlr.LexerBindings;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportUriResolver;

import uk.co.bithatch.eclipzpp.parser.antlr.lexer.FastPPLexer;
import uk.co.bithatch.eclipzpp.scoping.PPGlobalScopeProvider;
import uk.co.bithatch.eclipzpp.scoping.PPUriResolver;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PPRuntimeModule extends AbstractPPRuntimeModule {

	// configureRuntimeLexer is already generated in AbstractPPRuntimeModule and
	// binds the runtime lexer to InternalPPLexer. Only override it if you provide
	// your own Lexer implementation and its provider bindings.
	
	@Override
	public Class<? extends Lexer> bindLexer() {
		return FastPPLexer.class;
	}

	@Override
	public void configureRuntimeLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerBindings.RUNTIME)).to(FastPPLexer.class);
	}

	public Class<? extends ImportUriResolver> bindImportUriResolver() {
		return PPUriResolver.class;
	}
	
	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return PPGlobalScopeProvider.class;
	}
}
