/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipzpp.ui;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

public abstract class PPLabelProvider extends DefaultEObjectLabelProvider {

	private IPPOutlineModel model;

	public PPLabelProvider(IPPOutlineModel model, AdapterFactoryLabelProvider delegate) {
		super(delegate);
		this.model = model;
	}
	
	@Override
	protected Object doGetText(Object element) {
		var val = model.get(element.getClass());
		if(val != null) {
			if(val.childMapper() != null) {
				for(var child : val.childMapper().apply(element)) {
					Object rval = doGetText(child);
					if(rval != null) {
						return rval;
					}
				}
			}
			return val.textMapper().apply(element);
		}
		return super.doGetText(element);
	}

	@Override
	protected Object doGetImage(Object element) {
		var val = model.get(element.getClass());
		if(val != null) {
			if(val.childMapper() != null) {
				for(var child : val.childMapper().apply(element)) {
					Object rval = doGetImage(child);
					if(rval != null) {
						return rval;
					}
				}
			}
			return val.image();
		}
		return super.doGetImage(element);
	}


}
