/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipzpp.ui;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

public class PPOutlineTreeProvider extends DefaultOutlineTreeProvider {


	private final IPPOutlineModel model;

	public PPOutlineTreeProvider(IPPOutlineModel model) {
		this.model = model;
	}
	
	@Override
	protected boolean _isLeaf(final EObject modelElement) {
		  var mdl = model.get(modelElement.getClass());
		  return mdl == null || mdl.childMapper() == null;
	}
	
//	@Override
//	public void createChildren(IOutlineNode parent, EObject modelElement) {
//		var val = model.get(modelElement.getClass());
//		if(val != null) {
//			if(val.childMapper() != null) {
//				super.createChildren(parent, modelElement);
//			}
//		}
//	}
//	/**
//	 * Create children for the program root. Iterates lines and only creates nodes
//	 * for lines that contain structural elements (labels, directives).
//	 */
//	@Override
//	protected void _createChildren(IOutlineNode parentNode, AsmProgram program) {
//		for (AsmLine line : program.getLines()) {
//			if (isOutlineWorthy(line)) {
//				createNode(parentNode, line);
//			}
//		}
//	}
//
//	/**
//	 * Statement lines are always leaves in the outline (no need to drill into
//	 * instruction details).
//	 */
//	protected boolean _isLeaf(AsmStatementLine line) {
//		return true;
//	}
//
//	protected boolean _isLeaf(LabelledLine line) {
//		return true;
//	}
//
////	protected boolean _isLeaf(LabelEQULine line) {
////		return true;
////	}
//
////	protected boolean _isLeaf(AsmDefcLine line) {
////		return true;
////	}
//
//	protected boolean _isLeaf(AsmNumericLabelLine line) {
//		return true;
//	}
//
////	protected boolean _isLeaf(AsmLocalLine line) {
////		return true;
////	}
//
//	/**
//	 * Determines whether an AsmLine should appear in the outline.
//	 */
//	private boolean isOutlineWorthy(AsmLine line) {
//		// Label-only lines, EQU lines, DEFC lines, LOCAL lines, numeric labels - always show
//		if (line instanceof LabelledLine
////				|| line instanceof LabelEQULine
////				|| line instanceof AsmDefcLine
////				|| line instanceof AsmLocalLine
//				|| line instanceof AsmNumericLabelLine) {
//			return true;
//		}
//
//		// Statement lines - show if they have a label or contain a directive
//		if (line instanceof LabelledLine lol) {
//
//			// Has a label? Always show
//			if (lol.getName() != null) {
//				return true;
//			}
//
//			// Contains at least one directive? Show
//			for (AsmStatement stmt : lol.getStatements()) {
//				if (isDirective(stmt)) {
//					return true;
//				}
//			}
//
//			return false;
//		}
//
//		return false;
//	}
//
//	/**
//	 * Determines whether an AsmStatement is a directive (structural) rather than
//	 * a Z80 CPU instruction. Directives are shown in the outline; instructions
//	 * are not.
//	 */
//	private boolean isDirective(AsmStatement stmt) {
//		return stmt instanceof AsmOrg
//				|| stmt instanceof AsmInclude
//				|| stmt instanceof AsmModule
//				|| stmt instanceof AsmSection
//				|| stmt instanceof AsmAlignDirective
//				|| stmt instanceof AsmAssumeDirective
//				|| stmt instanceof AsmCallOzDirective
//				|| stmt instanceof AsmCallPkgDirective
////				|| stmt instanceof AsmBinaryDirective
//				|| stmt instanceof AsmCopperWaitDirective
//				|| stmt instanceof AsmCopperMoveDirective
//				|| stmt instanceof AsmCopperStopDirective
//				|| stmt instanceof AsmCopperNopDirective
//				|| stmt instanceof AsmDefByteDirective
//				|| stmt instanceof AsmDefWordDirective
//				|| stmt instanceof AsmDefWordBEDirective
//				|| stmt instanceof AsmDefPointerDirective
//				|| stmt instanceof AsmDefDWordDirective
//				|| stmt instanceof AsmDefTermStringDirective
//				|| stmt instanceof AsmDefSpaceDirective
//				|| stmt instanceof AsmDataDefineGroup
//				|| stmt instanceof AsmDataDefineVars
//				|| stmt instanceof AsmDMAWR0Directive
//				|| stmt instanceof AsmDMAWR1Directive
//				|| stmt instanceof AsmDMAWR2Directive
//				|| stmt instanceof AsmDMAWR3Directive
//				|| stmt instanceof AsmDMAWR4Directive
//				|| stmt instanceof AsmDMAWR5Directive
//				|| stmt instanceof AsmDMAWR6Directive
//				|| stmt instanceof AsmExternDirective
//				|| stmt instanceof AsmNextReg
//				|| stmt instanceof AsmMmuStatement
//				|| stmt instanceof AsmProcStatement;
//	}
}