/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipz80.ui.outline;

import java.util.stream.Stream;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import uk.co.bithatch.eclipz80.asm.AsmGroupedDefine;
import uk.co.bithatch.eclipz80.asm.AsmProgram;
import uk.co.bithatch.eclipz80.asm.LabelledLine;

public class AsmOutlineTreeProvider extends DefaultOutlineTreeProvider
{

	protected void _createChildren(IOutlineNode parentNode, AsmProgram program) {
		var dataRun = new DataRun(parentNode);

		program.getLines().stream().flatMap(ln -> {
			if(ln instanceof LabelledLine lln) {
				if(lln.getName() == null)  {
					return lln.getStatements().stream();
				}
				else {
					return Stream.concat(
						Stream.of(ln),
						lln.getStatements().stream()
					);
				}
			}
			else {
				return Stream.of(ln);
			}
		}).filter(this::isOutlineWorthy).forEachOrdered(dataRun::accept);

		dataRun.flush();
	}

	protected void _createChildren(IOutlineNode parentNode, LabelledLine lln) {
		lln.getStatements().stream().filter(this::isOutlineWorthy).forEach(ln -> createNode(parentNode, ln));
	}

	protected boolean _isLeaf(EObject line) {
		return !(line instanceof AsmGroupedDefine) && isOutlineWorthy(line);
	}

	private boolean isOutlineWorthy(EObject line) {

		if(AsmOutlineModel.isDirective(line)) {
			return true;
		}

		if (line instanceof LabelledLine lol) {
			return lol.getName() != null;
		}
		System.out.println("ZZZZZ " + line.getClass() + " is not worthy");
		return false;
	}

	private final class DataRun {
		private final IOutlineNode parentNode;
		private EObject firstData;
		private int count;

		private DataRun(IOutlineNode parentNode) {
			this.parentNode = parentNode;
		}

		private void accept(EObject line) {
			if (AsmOutlineModel.isData(line)) {
				if (firstData == null) {
					firstData = line;
					count = 1;
				}
				else {
					count++;
				}
				return;
			}

			flush();
			createNode(parentNode, line);
		}

		private void flush() {
			if (firstData == null) {
				return;
			}

			if (count == 1) {
				createNode(parentNode, firstData);
			}
			else {
				var mergedText = String.format("%s (x%d consecutive data directives)", _text(firstData), count);
				createEObjectNode(parentNode, firstData, _image(firstData), mergedText, _isLeaf(firstData));
			}

			firstData = null;
			count = 0;
		}
	}

}