/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.zxbasic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BasicStandaloneSetup extends BasicStandaloneSetupGenerated {

	public static void doSetup() {
		new BasicStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
