/*
 * generated by Xtext 2.43.0
 */
package uk.co.bithatch.eclipz80.scoping;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.resource.impl.ResourceImpl;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.EObjectDescription;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.SimpleScope;

import uk.co.bithatch.eclipz80.asm.AsmFactory;
import uk.co.bithatch.eclipz80.asm.AsmPackage;
import uk.co.bithatch.eclipz80.asm.AsmProgram;
import uk.co.bithatch.eclipzpp.DefineDef;
import uk.co.bithatch.eclipzpp.IMappedResource;

/**
 * This class contains custom scoping description.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AsmScopeProvider extends AbstractAsmScopeProvider {
	

	@Override
	public IScope getScope(EObject context, EReference reference) {
		IScope delegate = super.getScope(context, reference);
		if (reference == AsmPackage.eINSTANCE.getAsmLabel_Ref()) {

			var program = findProgram(context);
			var res = (IMappedResource)program.eResource();
			var defineObjects = new ArrayList<IEObjectDescription>();
			for(var def : res.map().defines().values()) {
				var stub = createDefineStub(def);
				var desc = EObjectDescription.create(QualifiedName.create(def.name()), stub);
				defineObjects.add(desc);
			}
			
			if(!defineObjects.isEmpty()) {
				delegate = new SimpleScope(delegate, defineObjects, true);
			}
			
			return new NamespaceRelativeLabelScope(delegate, AsmNamespaceSupport.namespacesBefore(context));
		}
		return delegate;
	}

	private EObject createDefineStub(DefineDef def) {
		var stub = AsmFactory.eINSTANCE.createAsmDefine(); 
		stub.setName(def.name());

		var dummyResource = new ResourceImpl(URI.createURI("asm://" + def.name()));
		dummyResource.getContents().add(stub);

		return stub;
	}

	private AsmProgram findProgram(EObject obj) {
		while (obj != null && !(obj instanceof AsmProgram)) {
			obj = obj.eContainer();
		}
		return (AsmProgram) obj;
	}

	private static final class NamespaceRelativeLabelScope implements IScope {
		private final IScope delegate;
		private final List<String> namespaces;

		private NamespaceRelativeLabelScope(IScope delegate, List<String> namespaces) {
			this.delegate = delegate;
			this.namespaces = namespaces;
		}

		@Override
		public IEObjectDescription getSingleElement(QualifiedName name) {
			if (name == null) {
				return null;
			}
			// Keep fully-qualified lookup untouched; only add relative lookup for single identifiers.
			if (name.getSegmentCount() == 1 && !namespaces.isEmpty()) {
				for (QualifiedName candidate : relativeCandidates(name)) {
					IEObjectDescription found = delegate.getSingleElement(candidate);
					if (found != null) {
						return found;
					}
				}
			}
			return delegate.getSingleElement(name);
		}

		@Override
		public Iterable<IEObjectDescription> getElements(QualifiedName name) {
			return delegate.getElements(name);
		}

		@Override
		public IEObjectDescription getSingleElement(EObject object) {
			return delegate.getSingleElement(object);
		}

		@Override
		public Iterable<IEObjectDescription> getElements(EObject object) {
			return delegate.getElements(object);
		}

		@Override
		public Iterable<IEObjectDescription> getAllElements() {
			return delegate.getAllElements();
		}

		private List<QualifiedName> relativeCandidates(QualifiedName leaf) {
			List<QualifiedName> candidates = new ArrayList<>();
			for (int i = namespaces.size(); i >= 1; i--) {
				List<String> segs = new ArrayList<>(namespaces.subList(0, i));
				segs.addAll(leaf.getSegments());
				candidates.add(QualifiedName.create(segs));
			}
			return candidates;
		}
	}
}