/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.zxbasic.scoping;

import java.util.ArrayList;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.impl.ResourceImpl;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.EObjectDescription;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.SimpleScope;

import com.google.inject.Inject;

import uk.co.bithatch.eclipzpp.IReferenceIndex;
import uk.co.bithatch.zxbasic.basic.BasicFactory;
import uk.co.bithatch.zxbasic.basic.BasicPackage;
import uk.co.bithatch.zxbasic.basic.Program;

/**
 * This class contains custom scoping description.
 * 
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ZXBasicScopeProvider extends AbstractBasicScopeProvider {
	@Inject
	private IReferenceIndex referenceIndex;
	
	@Override
	public IScope getScope(EObject context, EReference eRef) {
		var parent = super.getScope(context, eRef);
		if (eRef.equals(BasicPackage.Literals.REFERABLE_REF__REF)) {
			var program = findProgram(context);
			return addBuiltInFunctions(parent, program);
		}
		return parent;
	}

	private IScope addBuiltInFunctions(IScope parent, EObject context) {
		var builtIns = new ArrayList<IEObjectDescription>();

		for (var name : referenceIndex.definitions()) {
			var fname = name;
			var fakeFunc = createFunctionStub(fname);
			var desc = EObjectDescription.create(QualifiedName.create(fname), fakeFunc);
			builtIns.add(desc);
		}

		return new SimpleScope(parent, builtIns, true);
	}

	private EObject createFunctionStub(String name) {
		var stub = BasicFactory.eINSTANCE.createFunctionBlock(); 
		stub.setName(name);

		Resource dummyResource = new ResourceImpl(URI.createURI("zxb://" + name.toLowerCase()));
		dummyResource.getContents().add(stub);

		return stub;
	}

	private Program findProgram(EObject obj) {
		while (obj != null && !(obj instanceof Program)) {
			obj = obj.eContainer();
		}
		return (Program) obj;
	}
}
