/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.zxbasic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AsmUiModule extends AbstractAsmUiModule {

	public AsmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
