/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.zxbasic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.resource.ILocationInFileProvider;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;

import uk.co.bithatch.zxbasic.IIncludeSource;
import uk.co.bithatch.zxbasic.ILanguageSettings;
import uk.co.bithatch.zxbasic.IReferenceIndex;
import uk.co.bithatch.zxbasic.ui.contentassist.BasicReferenceIndex;
import uk.co.bithatch.zxbasic.ui.contentassist.ProjectPreferencesLanguageSettings;
import uk.co.bithatch.zxbasic.ui.library.ZXBasicLibraryIncludeSource;
import uk.co.bithatch.zxbasic.ui.outline.ZXBasicOutlineTreeProvider;
import uk.co.bithatch.zxbasic.ui.preprocessing.ZXBasicLocationInFileProvider;
import uk.co.bithatch.zxbasic.ui.preprocessing.ZXBasicResource;
import uk.co.bithatch.zxbasic.ui.syntaxcoloring.ZXBasicHighlightingConfiguration;
import uk.co.bithatch.zxbasic.ui.syntaxcoloring.ZXBasicSemanticHighlightingCalculator;
import uk.co.bithatch.zxbasic.ui.syntaxcoloring.ZXBasicTokenToAttributeMapper;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BasicUiModule extends AbstractBasicUiModule {

	public BasicUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	public Class<? extends ILocationInFileProvider> bindILocationInFileProvider() {
	    return ZXBasicLocationInFileProvider.class;
	}
	
	public Class<? extends XtextResource> bindXtextResource() {
	    return ZXBasicResource.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
	    return ZXBasicSemanticHighlightingCalculator.class;
	}
	public Class<? extends ILanguageSettings> bindILanguageSettings() {
	    return ProjectPreferencesLanguageSettings.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return ZXBasicHighlightingConfiguration.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return ZXBasicTokenToAttributeMapper.class;
	}

	@Override
	public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
		return ZXBasicOutlineTreeProvider.class;
	}
	
//	@Override
//	public Class<? extends ITextHover> bindITextHover() {
//	    return ZXBasicTextHover.class;
//	}

	public Class<? extends IReferenceIndex> bindIReferenceIndex() {
	    return BasicReferenceIndex.class;
	}

	public Class<? extends IIncludeSource> bindIIncludeSource() {
	    return ZXBasicLibraryIncludeSource.class;
	}
	
//	public Class<? extends IResourceUIValidatorExtension> bindResourceUIValidatorExtension() {
//	    return ZXBasicResourceUIValidatorExtension.class;
//	}
//
//    public Class<? extends IssueSeveritiesProvider> bindIssueSeveritiesProvider() {
//        return ZXBasicIssueSeveritiesProvider.class;
//    }

}
