# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ZXBasic

on:
  pull_request:
    branches-ignore:
      - docs

env:
  PYTHON_VERSION: 3.12.3

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.head_ref != 'docs'  # Ignore test runs for docs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install poetry
      run: |
        pip install -U pip~=24.0
        pip install poetry~=1.7.1
        poetry config virtualenvs.in-project true

    - name: Set up poetry cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-py-${{ env.PYTHON_VERSION }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
      run: poetry install --verbose

    - name: Lint code
      run: poetry run poe lint

    - name: Run tests
      run: poetry run poe test
