/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipz80.ui;

import org.eclipse.jface.text.hyperlink.IHyperlinkDetector;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.ui.editor.XtextEditor;

import uk.co.bithatch.eclipz80.AsmIncludeSource;
import uk.co.bithatch.eclipz80.ui.debug.AsmXtextEditor;
import uk.co.bithatch.eclipz80.ui.hyperlinking.AsmHyperlinkDetector;
import uk.co.bithatch.eclipz80.ui.library.AsmLibraryIncludeSource;
import uk.co.bithatch.eclipz80.ui.outline.AsmOutlineModel;
import uk.co.bithatch.eclipz80.ui.preprocessing.AsmReferenceIndex;
import uk.co.bithatch.eclipz80.ui.preprocessing.AsmResource;
import uk.co.bithatch.eclipz80.ui.syntaxcoloring.AsmHighlightingConfiguration;
import uk.co.bithatch.eclipz80.ui.syntaxcoloring.AsmSemanticHighlightingCalculator;
import uk.co.bithatch.eclipz80.ui.syntaxcoloring.AsmTokenToAttributeMapper;
import uk.co.bithatch.eclipzpp.IReferenceIndex;
import uk.co.bithatch.eclipzpp.ui.IPPOutlineModel;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AsmUiModule extends AbstractAsmUiModule {

	public AsmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends XtextResource> bindXtextResource() {
	    return AsmResource.class;
	}
//
//	public Class<? extends ILocationInFileProvider> bindILocationInFileProvider() {
//	    return AsmLocationInFileProvider.class;
//	}

	public Class<? extends IPPOutlineModel> bindIPPOutlineModel() {
	    return AsmOutlineModel.class;
	}

	public Class<? extends IReferenceIndex> bindIReferenceIndex() {
	    return AsmReferenceIndex.class;
	}

	public Class<? extends AsmIncludeSource> bindIAsmIncludeSource() {
	    return AsmLibraryIncludeSource.class;
	}

	public Class<? extends IHyperlinkDetector> bindIHyperlinkDetector() {
	    return AsmHyperlinkDetector.class;
	}

	public Class<? extends XtextEditor> bindXtextEditor() {
		return AsmXtextEditor.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
	    return AsmSemanticHighlightingCalculator.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return AsmHighlightingConfiguration.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return AsmTokenToAttributeMapper.class;
	}
}
