/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipz80.ui.labeling;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import uk.co.bithatch.eclipz80.asm.AsmDefWordDirective;
import uk.co.bithatch.eclipz80.asm.AsmDefine;
import uk.co.bithatch.eclipz80.asm.AsmExpression;
import uk.co.bithatch.eclipz80.asm.AsmIncBin;
import uk.co.bithatch.eclipz80.asm.AsmInclude;
import uk.co.bithatch.eclipz80.asm.AsmLabel;
import uk.co.bithatch.eclipz80.asm.AsmProgram;
import uk.co.bithatch.eclipz80.asm.DataDefineGroup;
import uk.co.bithatch.eclipz80.asm.DefByte;
import uk.co.bithatch.eclipz80.asm.DefC;
import uk.co.bithatch.eclipz80.asm.DefDWord;
import uk.co.bithatch.eclipz80.asm.DefPointer;
import uk.co.bithatch.eclipz80.asm.DefTermString;
import uk.co.bithatch.eclipz80.asm.DefWord;
import uk.co.bithatch.eclipz80.asm.DefWordBE;
import uk.co.bithatch.eclipz80.asm.Define;
import uk.co.bithatch.eclipz80.asm.IntegralLiteral;
import uk.co.bithatch.eclipz80.asm.LabelledLine;
import uk.co.bithatch.eclipz80.asm.Org;
import uk.co.bithatch.eclipz80.asm.StringLiteral;
import uk.co.bithatch.eclipz80.generator.ModelHelpers;
import uk.co.bithatch.eclipz80.ui.AsmUiActivator;
import uk.co.bithatch.eclipz80.ui.outline.AsmOutlineModel;
import uk.co.bithatch.eclipzpp.ui.PPUiActivator;

/**
 * Provides labels and icons for EObjects in the outline view.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class AsmLabelProvider extends/* PPLabelProvider*/ DefaultEObjectLabelProvider {

//	@Inject
//	public AsmLabelProvider(IPPOutlineModel model, AdapterFactoryLabelProvider delegate) {
//		super(model, delegate);
//	}

	// ─────────────── Labels ───────────────

	String text(LabelledLine ele) {
		return ele.getName() != null ? ele.getName().getName() : "<label>";
	}

//	String text(AsmDefcLine ele) {
//		return ele.getName() != null ? "DEFC " + ele.getName().getName() : "DEFC";
//	}

//	String text(AsmLocalLine ele) {
//		StringBuilder sb = new StringBuilder("LOCAL ");
//		if (ele.getLabels() != null && !ele.getLabels().isEmpty()) {
//			sb.append(String.join(", ", ele.getLabels()));
//		}
//		return sb.toString();
//	}

//	String text(LabelledLine ele) {
//		StringBuilder sb = new StringBuilder();
//		if (ele.getName() != null) {
//			sb.append(ele.getName().getName());
//		}
//		if (ele.getStatements() != null && !ele.getStatements().isEmpty()) {
//			for (AsmStatement stmt : ele.getStatements()) {
//				String stmtText = getStatementText(stmt);
//				if (stmtText != null) {
//					if (sb.length() > 0) sb.append(": ");
//					sb.append(stmtText);
//				}
//			}
//		}
//		return sb.length() > 0 ? sb.toString() : "<statement>";
//	}
//
	String text(Org ele) {
		return "ORG " + formatIntegralLiteral(ModelHelpers.resolveIntegralLiteral(ele.getValue()));
	}
//
//	String text(uk.co.bithatch.eclipz80.asm.Module ele) {
//		return "MODULE " + (ele.getName() != null ? ele.getName() : "");
//	}
//
//	String text(Section ele) {
//		return "SECTION " + (ele.getName() != null ? ele.getName() : "");
//	}
//
//	String text(Extern ele) {
//		if (ele.getName() != null && !ele.getName().isEmpty()) {
//			return "EXTERN " + String.join(", ", ele.getName().stream().map(e -> e.getName()).toList());
//		}
//		return "EXTERN";
//	}
//
////	String text(IncBin ele) {
////		return "INCBIN " + (ele.getFile() != null ? ele.getFile() : "");
////	}
//
//	String text(Proc ele) {
//		return "PROC";
//	}
//
	String text(DataDefineGroup ele) {
		return ele.getName();
	}
	
	String text(Define defc) {
		return defc.getName() == null ? "??" : defc.getName().getName();
	}

	String text(DefByte def) {
		return eval(def.getData());
	}

	String text(DefWord def) {
		return eval(def.getData());
	}

	String text(DefWordBE def) {
		return eval(def.getData());
	}

	String text(DefPointer def) {
		return eval(def.getData());
	}

	String text(DefDWord def) {
		return eval(def.getData());
	}

	String text(DefTermString def) {
		return eval(def.getData());
	}

	String text(DefC defc) {
		return defc.getName() == null ? "??" : defc.getName().getName();
	}

	// ─────────────── Icons ───────────────

//	String image(LabelEQULine ele) {
//		return "outline-equ.png";
//	}

//	String image(AsmDefcLine ele) {
//		return "outline-equ.png";
//	}
//
	Object image(AsmProgram prg) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.PROGRAM_PATH);
	}
	
	Object image(AsmDefine def) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.DEFINE_PATH);
	}

	Object image(EObject fallback) {
		if(AsmOutlineModel.isData(fallback))
			return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.DATA_PATH);
		else if(AsmOutlineModel.isConstant(fallback))
			return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.LOCAL_PATH);
		else
			return null;
	}

	Object image(AsmDefWordDirective prg) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.DATA_PATH);
	}
	
	Object image(LabelledLine ele) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.LABEL_PATH);
	}
//
	Object image(Org ele) {
		return AsmUiActivator.getInstance().getImageRegistry().getDescriptor(AsmUiActivator.ORG_PATH);
	}
	
//	String image(AsmModule ele) {
//		return "outline-module.png";
//	}
//
//	String image(AsmSection ele) {
//		return "outline-section.png";
//	}
//
//	String image(Extern ele) {
//		return "outline-extern.png";
//	}

//	String image(Proc ele) {
//		return "outline-proc.png";
//	}
//
//	String image(DataDefineGroup ele) {
//		return "outline-data.png";
//	}

	Object image(AsmIncBin ele) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.INCLUDE_PATH);
	}

	Object image(AsmInclude ele) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.INCLUDE_PATH);
	}

	// ─────────────── Helpers ───────────────

//	private String getStatementText(AsmStatement stmt) {
//		if (stmt instanceof Org) {
//			return "ORG " + formatIntegralLiteral(((Org) stmt).getValue());
//		} else if (stmt instanceof uk.co.bithatch.eclipz80.asm.Module) {
//			return "MODULE " + ((uk.co.bithatch.eclipz80.asm.Module) stmt).getName();
//		} else if (stmt instanceof Section) {
//			return "SECTION " + ((Section) stmt).getName();
//		} else if (stmt instanceof AsmInclude) {
//			return "INCLUDE " + ((AsmInclude) stmt).getImportURI();
//		} else if (stmt instanceof Extern) {
//			Extern ext = (Extern) stmt;
//			return "EXTERN " + (ext.getName() != null ? String.join(", ", ext.getName().stream().map(e -> e.getName()).toList()) : "");
////		} else if (stmt instanceof IncBin) {
////			return "INCBIN " + ((IncBin) stmt).getFile();
//		} 
//		else if (stmt instanceof Proc) {
//			return "PROC";
//		} else if (stmt instanceof AsmDefByteDirective) {
//			return "DEFB";
//		} else if (stmt instanceof AsmDefWordDirective) {
//			return "DEFW";
//		} else if (stmt instanceof AsmDefSpaceDirective) {
//			return "DEFS";
//		} else if (stmt instanceof AsmAlignDirective) {
//			return "ALIGN";
//		} else if (stmt instanceof AsmNextReg) {
//			return "NEXTREG";
//		} else if (stmt instanceof AsmMmuStatement) {
//			return "MMU";
//		} else if (stmt instanceof AsmDataDefineGroup) {
//			return "DEFGROUP";
//		} else if (stmt instanceof AsmDataDefineVars) {
//			return "DEFVARS";
//		}
//		// Generic directive fallback
//		return stmt.eClass().getName();
//	}
//
//	private Object getStatementIcon(AsmStatement stmt) {
//		if (stmt instanceof AsmOrg) return "outline-org.png";
//		if (stmt instanceof AsmModule) return "outline-module.png";
//		if (stmt instanceof AsmSection) return "outline-section.png";
//		if (stmt instanceof AsmExternDirective) return "outline-extern.png";
////		if (stmt instanceof AsmBinaryDirective) return "outline-include.png";
//		if (stmt instanceof AsmProcStatement) return "outline-proc.png";
//		if (stmt instanceof AsmDataDefineGroup || stmt instanceof AsmDataDefineVars) return "outline-data.png";
//		if (stmt instanceof AsmDefByteDirective || stmt instanceof AsmDefWordDirective
//				|| stmt instanceof AsmDefWordBEDirective || stmt instanceof AsmDefPointerDirective
//				|| stmt instanceof AsmDefDWordDirective || stmt instanceof AsmDefTermStringDirective
//				|| stmt instanceof AsmDefSpaceDirective) return "outline-data.png";
//		return "outline-directive.png";
//	}
//
	
	private String eval(List<AsmExpression> expressions) {
		return String.join(", ", expressions.stream().map(this::eval).toList());
	}
	
	private String eval(AsmExpression expression) {
		if(expression instanceof AsmLabel asmlabel) {
			return asmlabel.getRef().getName();
		}
		else if(expression instanceof StringLiteral slit) {
			return slit.getValue();
		}
		else if(expression instanceof IntegralLiteral ilit) {
			return String.valueOf(ilit.getValue());
		}
		else  {
		
			EObject eObject = (EObject) expression;
			EStructuralFeature labelFeature = getLabelFeature(eObject.eClass());
			if(labelFeature != null) {
				return String.valueOf(expression.eGet(labelFeature));
			}
			return "??";
		
		}
	}
	
	private String formatIntegralLiteral(int val) {
		return String.format("%04x (%5d)", val, val);
	}
}
