/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipz80.ui.labeling;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import uk.co.bithatch.eclipz80.asm.AsmExpression;
import uk.co.bithatch.eclipz80.asm.AsmGlobalDirective;
import uk.co.bithatch.eclipz80.asm.AsmIncBin;
import uk.co.bithatch.eclipz80.asm.AsmInclude;
import uk.co.bithatch.eclipz80.asm.AsmLabel;
import uk.co.bithatch.eclipz80.asm.AsmProgram;
import uk.co.bithatch.eclipz80.asm.AsmPushNamespace;
import uk.co.bithatch.eclipz80.asm.DataDefineGroup;
import uk.co.bithatch.eclipz80.asm.DefByte;
import uk.co.bithatch.eclipz80.asm.DefC;
import uk.co.bithatch.eclipz80.asm.DefDWord;
import uk.co.bithatch.eclipz80.asm.DefPointer;
import uk.co.bithatch.eclipz80.asm.DefTermString;
import uk.co.bithatch.eclipz80.asm.DefWord;
import uk.co.bithatch.eclipz80.asm.DefWordBE;
import uk.co.bithatch.eclipz80.asm.Define;
import uk.co.bithatch.eclipz80.asm.Extern;
import uk.co.bithatch.eclipz80.asm.Global;
import uk.co.bithatch.eclipz80.asm.IntegralLiteral;
import uk.co.bithatch.eclipz80.asm.LabelledLine;
import uk.co.bithatch.eclipz80.asm.Org;
import uk.co.bithatch.eclipz80.asm.Public;
import uk.co.bithatch.eclipz80.asm.Push;
import uk.co.bithatch.eclipz80.asm.StringLiteral;
import uk.co.bithatch.eclipz80.assembler.ModelHelpers;
import uk.co.bithatch.eclipz80.ui.AsmUiActivator;
import uk.co.bithatch.eclipz80.ui.outline.AsmOutlineModel;
import uk.co.bithatch.eclipzpp.ui.PPUiActivator;

/**
 * Provides labels and icons for EObjects in the outline view.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class AsmLabelProvider extends/* PPLabelProvider*/ DefaultEObjectLabelProvider {

	// Labels
	String text(LabelledLine ele) {
		return ele.getName() != null ? ele.getName().getName() : "<label>";
	}

	String text(Org ele) {
		return "ORG " + formatIntegralLiteral(ModelHelpers.resolveIntegralLiteral(ele.getValue()));
	}

	String text(DataDefineGroup ele) {
		return ele.getName() == null ? "??" : ele.getName();
	}
	
	String text(Define defc) {
		return defc.getName() == null ? "??" : defc.getName().getName();
	}

	String text(DefByte def) {
		return eval(def.getData());
	}

	String text(DefWord def) {
		return eval(def.getData());
	}

	String text(DefWordBE def) {
		return eval(def.getData());
	}

	String text(DefPointer def) {
		return eval(def.getData());
	}

	String text(DefDWord def) {
		return eval(def.getData());
	}

	String text(DefTermString def) {
		return eval(def.getData());
	}

	String text(DefC defc) {
		return defc.getName() == null ? "??" : defc.getName().getName();
	}

	String text(Global defc) {
		return String.join(", ", defc.getName().stream().map(e -> e.getRef().getName()).toList());
	}

	String text(uk.co.bithatch.eclipz80.asm.Module mod) {
		return mod.getName();
	}
	
	String text(Extern extern) {
		return String.join(", ", extern.getName().stream().map(e -> e.getRef().getName()).toList());
	}

	String text(Push ns) {
		return ns.getNamespace() == null ? "??" : ns.getNamespace().getImportedNamespace();
	}

	// Icons
//
	Object image(AsmProgram prg) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.PROGRAM_PATH);
	}
	
	Object module(uk.co.bithatch.eclipz80.asm.Module mod) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.MODULE_PATH);
	}
	
	Object image(Define def) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.DEFINE_PATH);
	}
	
	Object image(Extern extern) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.EXTERN_PATH);
	}
	
	Object image(Push ns) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.NS_PATH);
	}
	
	Object image(EObject fallback) {
		if(AsmOutlineModel.isData(fallback))
			return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.DATA_PATH);
		else if(AsmOutlineModel.isSymbol(fallback)) {
			var symlab = AsmOutlineModel.symbolLabel(fallback);
			var it = fallback.eResource().getAllContents();
			while(it.hasNext()) {
				var nxt = it.next();
				if(nxt instanceof Public pub && pub.getName().stream().map(e -> e.getRef().getName()).toList().contains(symlab)) {
					return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.PUBLIC_PATH);					
				}
				else if(nxt instanceof Global glob && glob.getName().stream().map(e -> e.getRef().getName()).toList().contains(symlab)) {
					return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.PUBLIC_PATH);					
				}
			}
			
			if(fallback instanceof  AsmGlobalDirective) {
				return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.EXTERN_PATH);
			}
			else {
				return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.LOCAL_PATH);
			}
		}
		else
			return null;
	}
	
	Object image(LabelledLine ele) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.LABEL_PATH);
	}
//
	Object image(Org ele) {
		return AsmUiActivator.getInstance().getImageRegistry().getDescriptor(AsmUiActivator.ORG_PATH);
	}
	
	Object image(AsmIncBin ele) {
		return AsmUiActivator.getInstance().getImageRegistry().getDescriptor(AsmUiActivator.INCBIN_PATH);
	}

	Object image(AsmInclude ele) {
		return PPUiActivator.getDefault().getImageRegistry().getDescriptor(PPUiActivator.INCLUDE_PATH);
	}

	
	private String eval(List<AsmExpression> expressions) {
		return String.join(", ", expressions.stream().map(this::eval).toList());
	}
	
	private String eval(AsmExpression expression) {
		if(expression instanceof AsmLabel asmlabel) {
			return asmlabel.getRef().getName();
		}
		else if(expression instanceof StringLiteral slit) {
			return slit.getValue();
		}
		else if(expression instanceof IntegralLiteral ilit) {
			return String.valueOf(ilit.getValue());
		}
		else  {
		
			EObject eObject = (EObject) expression;
			EStructuralFeature labelFeature = getLabelFeature(eObject.eClass());
			if(labelFeature != null) {
				return String.valueOf(expression.eGet(labelFeature));
			}
			return "??";
		
		}
	}
	
	private String formatIntegralLiteral(int val) {
		return String.format("%04x (%5d)", val, val);
	}
}
