/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.eclipz80;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AsmStandaloneSetup extends AsmStandaloneSetupGenerated {

	public static void doSetup() {
		new AsmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public void register(Injector injector) {
		super.register(injector);
		// Also register .inc files so they can be parsed as Asm resources
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("inc", resourceFactory);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("hdr", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("inc", serviceProvider);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("hdr", serviceProvider);
	}
}
