site_name: ZX Basic Wiki
nav:
  - Home: index.md
  - Syntax: syntax.md
  - Reserved Words: identifier.md
  - Tutorials: tutorials.md
  - External Resources: external_resources.md
  - About: about.md

theme:
  name: readthedocs

docs_dir: docs

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
