package uk.co.bithatch.drawzx.wizards;

import org.eclipse.core.resources.IContainer;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IFolder;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.resources.IWorkspace;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.Path;
import org.eclipse.jface.fieldassist.ControlDecoration;
import org.eclipse.jface.layout.GridDataFactory;
import org.eclipse.jface.window.Window;
import org.eclipse.jface.wizard.WizardPage;
import org.eclipse.swt.SWT;
import org.eclipse.swt.events.SelectionAdapter;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.FileDialog;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Text;
import org.eclipse.ui.ISharedImages;
import org.eclipse.ui.PlatformUI;
import org.eclipse.ui.dialogs.ContainerSelectionDialog;

import uk.co.bithatch.zyxy.graphics.Palette;

public class PaletteImportWizardPage extends WizardPage {

	private Text fileText;
	private Text destText;
	private Text nameText;
	private Button overrite;
	private ControlDecoration destDecoration;
	private ControlDecoration srcDecoration;
	private ControlDecoration nameDecoration;
	private Button outputPalFormat;
	private Button outputNplFormat;
	private Button autoFormat;
	private Palette cachedPal;

	protected PaletteImportWizardPage(String pageName) {
		super(pageName);
		setTitle("Import Palette File");
		setDescription("Import a palette generated by a 3rd party tool to be "
				+ "edited as a ZX Next 256 or 256+1 colour palette.");
	}

	@Override
	public void createControl(Composite parent) {

		var stateUpdate = new SelectionAdapter() {
			@Override
			public void widgetSelected(SelectionEvent e) {
				updateState();
			}
		};
		var container = new Composite(parent, SWT.NONE);
		var layout = new GridLayout(3, false);
		layout.verticalSpacing = 8;
		layout.horizontalSpacing = 16;
		container.setLayout(layout);

		var fileLabel = new Label(container, SWT.NONE);
		fileLabel.setText("Source File:");
		fileText = new Text(container, SWT.BORDER);
		fileText.setLayoutData(new GridData(GridData.FILL_HORIZONTAL));
		fileText.addModifyListener(e -> {
			cachedPal = null;
			updateState(); 
		});

		srcDecoration = new ControlDecoration(fileText, SWT.LEFT | SWT.TOP);
		srcDecoration.setImage(PlatformUI.getWorkbench().getSharedImages().getImage(ISharedImages.IMG_OBJS_ERROR_TSK));
		srcDecoration.setDescriptionText("Import file does not exist.");
		srcDecoration.hide();

		var browseButton = new Button(container, SWT.PUSH);
		browseButton.setText("Browse...");
		browseButton.addListener(SWT.Selection, e -> {
			FileDialog dialog = new FileDialog(getShell(), SWT.OPEN);
			dialog.setFilterExtensions(
					new String[] { "*.act;*.gpl;*.pal;*.txt", "*.act", "*.gpl", "*.pal", "*.txt", "*.*" });
			dialog.setFilterNames(new String[] { "All supported types (*.act, *.gpl, *.pal, *.txt)",
					"Photoshop (*.act)", "GIMP (*.gpl)", "JASC-PAL (*.pal)", "Paint.NET (*.txt)", "All file types" });
			String result = dialog.open();
			if (result != null) {
				fileText.setText(result);
				if (nameText.getText().trim().equals("")) {
					nameText.setText(stripExtension(getSourcePath().lastSegment()));
				}
			}
		});

		Label destLabel = new Label(container, SWT.NONE);
		destLabel.setText("Destination folder:");
		destText = new Text(container, SWT.BORDER);
		destText.setLayoutData(new GridData(GridData.FILL_HORIZONTAL));
		destText.addModifyListener(e -> updateState());

		destDecoration = new ControlDecoration(destText, SWT.LEFT | SWT.TOP);
		destDecoration.setImage(PlatformUI.getWorkbench().getSharedImages().getImage(ISharedImages.IMG_OBJS_ERROR_TSK));
		destDecoration.setDescriptionText("Destination does not exist.");
		destDecoration.hide();

		Button browseDestButton = new Button(container, SWT.PUSH);
		browseDestButton.setText("Browse...");
		browseDestButton.addListener(SWT.Selection, e -> {

			ContainerSelectionDialog projDialog = new ContainerSelectionDialog(getShell(),
					PlatformUI.getWorkbench().getAdapter(IWorkspace.class).getRoot(), true,
					"Select a folder from your workspace");
			if (projDialog.open() == Window.OK) {
				Object[] selected = projDialog.getResult();
				if (selected.length > 0) {
					IPath path = (IPath) selected[0];
					destText.setText(path.toPortableString());
					updateState();
				}
			}
		});

		Label nameLabel = new Label(container, SWT.NONE);
		nameLabel.setText("Palette filename:");
		nameText = new Text(container, SWT.BORDER);
		nameText.setLayoutData(new GridData(GridData.FILL_HORIZONTAL));
		nameText.addModifyListener(e -> updateState());

		nameDecoration = new ControlDecoration(nameText, SWT.LEFT | SWT.TOP);
		palExists();
		nameDecoration.hide();
		new Label(container, SWT.NONE);

		overrite = new Button(container, SWT.CHECK);
		overrite.setText("Overwrite existing file");
		overrite.setLayoutData(GridDataFactory.fillDefaults().span(3, 1).create());
		overrite.addSelectionListener(stateUpdate);
		
		var sep = new Label(container,SWT.SEPARATOR);
		sep.setLayoutData(GridDataFactory.fillDefaults().span(3, 1).create());
		
		Label formatLabel = new Label(container, SWT.NONE);
		formatLabel.setText("Palette Format:");
		autoFormat = new Button(container, SWT.RADIO);
		autoFormat.setSelection(true);
		autoFormat.setText("Automatic based on source palette");
		autoFormat.setLayoutData(GridDataFactory.fillDefaults().span(2, 1).create());
		autoFormat.addSelectionListener(stateUpdate);
		new Label(container, SWT.NONE);
        outputPalFormat = new Button(container, SWT.RADIO);
        outputPalFormat.setText("ZX Next PAL (256 Colours)");
        outputPalFormat.setLayoutData(GridDataFactory.fillDefaults().span(2, 1).create());
		outputPalFormat.addSelectionListener(stateUpdate);
		new Label(container, SWT.NONE);
        outputNplFormat = new Button(container, SWT.RADIO);
        outputNplFormat.setText("ZX Next NPL (256+1 Colours)");
        outputNplFormat.setLayoutData(GridDataFactory.fillDefaults().span(2, 1).create());
		outputNplFormat.addSelectionListener(stateUpdate);

		// Project folder

		setControl(container);
		updateState();
	}

	public IPath getSourcePath() {
		return new Path(fileText.getText().trim());
	}

	public IFolder getTargetFolder() {
		return (IFolder) getTargetResource();
	}

	private IResource getTargetResource() {
		return ResourcesPlugin.getWorkspace().getRoot().findMember(destText.getText().trim());
	}

	public IFile getTargetPath() {
		var fname = nameText.getText().trim();
		var extension = stripExtension(fname);
		try {
			var fullPath = getTargetResource();
			var tname = extension.equals(fname) ? fname + "." + getExtension() : fname;
			if(fullPath instanceof IProject iprj) {
				return iprj.getFile(tname);
			}
			else if(fullPath instanceof IFolder ifldr) {
				return ifldr.getFile(tname);
			}
		} catch (Exception e) {
		}
		return null;
	}

	public String getExtension() {
		if(outputPalFormat.getSelection())
			return "pal";
		else if(outputNplFormat.getSelection())
			return "npl";
		else {
			try {
				if(cachedPal == null) {
					cachedPal = PaletteImportWizard.loadPalette(getSourcePath().toPath());	
				}
				if(cachedPal.size() > 256) {
					return "npl";
				}
			} catch (Exception e) {
			}
			return "pal";
		}
	}

	private void updateState() {
		var targetFile = getTargetPath();
		var sourceExists = getSourcePath().toFile().exists();
		var targetRes = getTargetResource();
		var targetResExists = targetRes != null && targetRes.exists();
		var targetFolderExists = targetResExists && targetRes instanceof IContainer;
		var overwriteTarget = overrite.getSelection();

		setVisible(srcDecoration, !sourceExists && fileText.getText().length() > 0);
		setVisible(destDecoration, !targetFolderExists);
		if (targetFile == null) {
			overrite.setEnabled(false);
			setPageComplete(false);
			if(destText.getText().length() > 0) {
				setErrorMessage("The destination folder does not exist.");
			}
			else if (!sourceExists) {
				setErrorMessage("The source file does not exist.");
			} else {
				setErrorMessage(null);
			}
		} else {
			overrite.setEnabled(targetFile.exists());
			if (targetFile.exists() && !overwriteTarget) {
				palExists();
				setVisible(nameDecoration, true);
				setPageComplete(false);
				setErrorMessage("Target palette file exists, overwrite or chose a different name");
			} else {
				if (targetFile.getName().toLowerCase().endsWith(".pal") || targetFile.getName().toLowerCase().endsWith(".npl")) {
					setVisible(nameDecoration, false);
				} else {
					nameDecoration.setImage(
							PlatformUI.getWorkbench().getSharedImages().getImage(ISharedImages.IMG_OBJS_WARN_TSK));
					nameDecoration.setDescriptionText("Palette file name should ideally end with .pal.");
					setVisible(nameDecoration, true);
				}
				setPageComplete(sourceExists && targetFolderExists && (!targetFile.exists() || overwriteTarget));
				if (sourceExists) {
					if (targetFolderExists)
						setErrorMessage(null);
					else
						setErrorMessage("The destination folder does not exist.");
				} else {
					setErrorMessage("The source file does not exist.");
				}
			}
		}
	}

	private static void setVisible(ControlDecoration ctrl, boolean vis) {
		if (vis)
			ctrl.show();
		else
			ctrl.hide();
	}

	private static String stripExtension(String p) {
		var i = p.lastIndexOf('.');
		return i == -1 ? p : p.substring(0, i);
	}

	private void palExists() {
		nameDecoration.setImage(PlatformUI.getWorkbench().getSharedImages().getImage(ISharedImages.IMG_OBJS_ERROR_TSK));
		nameDecoration.setDescriptionText("Target palette file already exists.");
	}
}
