/*
 * generated by Xtext 2.39.0
 */
package uk.co.bithatch.zxbasic.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.co.bithatch.zxbasic.AsmRuntimeModule;
import uk.co.bithatch.zxbasic.AsmStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AsmIdeSetup extends AsmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AsmRuntimeModule(), new AsmIdeModule()));
	}
	
}
